var CONFIG_NAMES = {
    en: {
        "playerStartMass": strData(null, "حجم بداية اللاعب"),
        "playerMaxCells": strData(null, "أكبر عدد من الخلايا المسموح بها لكل لاعب"),
        "playerSpeed": strData(null, "Player speed multiplier (1=normal speed, 2=twice faster)"),
        "playerDecayRate": strData(null, "الحجم الذي يتم فقدانه كل ثانية"),
        "playerRecombineTime": strData(null, "الوقت الذي يحتاجه اللاعب قبل أن يتجمع"),
        "ejectSize": strData(null, "حجم القذف"),
        "ejectSizeLoss": strData(null, "الحجم الذي سيتم فقدانه من اللاعب"),
        "ejectDistance": strData(null, "مسافة القذف"),
        "ejectCooldown": strData(null, "Tick count until a player can eject mass again (1 tick = 40 ms)"),
        "foodMinSize": strData(null, "الحجم القصوي للطعام"),
        "foodMinAmount": strData(null, "أقل عدد خلايا الطعام"),
        "virusMinSize": strData(null, "أقل حجم للفيروس"),
        "virusMinAmount": strData(null, "أقل عدد الفيروسات في الخريطة"),
        "speedBoosterMinAmount": strData(null, "عدد رافعي الطاقة للسرعة"),
        "speedBoosterTime": strData(null, "كم من الوقت ستقوم بالإشتغال"),
        "speedBoosterValue": strData(null, "Multiplyer of speed (1.5 = 50% faster, 0.5 = 50% slower"),
        "speedBoosterSize": strData(null, "حجم رافع الطاقة"),
        "mergeBoosterMinAmount": strData(null, "عدد رافع الطاقة للتجمع"),
        "mergeBoosterTime": strData(null, "كم من الوقت ستقوم بالإستغال"),
        "mergeBoosterValue": strData(null, "Multiplyer of recombine time (0.5 = 50% faster, 1.5 = 50% slower)"),
        "mergeBoosterSize": strData(null, "كم حجم رافع الطاقة"),
        "virusBoosterMinAmount": strData(null, "عدد فيروسات رافع الطاقة"),
        "virusBoosterTime": strData(null, "كم من الوقت ستقوم بالإستغال"),
        "virusBoosterSize": strData(null, "كم حجم رافع الطاقة"),
        "sizeBoosterMinAmount": strData(null, "كمية رافع الطاقة للحجم"),
        "sizeBoosterTime": strData(null, "كم من الوقت ستقوم بالإستغال"),
    },
    ru: {
        "playerStartMass": strData("стартМасса", "Стартовая масса шара игрока"),
        "playerMaxCells": strData("максКолШаров", "Максимальное количество шаров которое игрок может иметь"),
        "playerSpeed": strData("скорДвижИгрока", "Множитель скорости игрока (1=стандартная, 2=в два раза быстрее)"),
        "playerDecayRate": strData("скорПотериМассы", "Скорость потерми массы игроком"),
        "playerRecombineTime": strData("скорСоедШаров", "Базовое время в секунда перед тем как шару позволяется соедениться"),
        "ejectSize": strData("размЕджекта", "Размер еджекта"),
        "ejectSizeLoss": strData("ушербЕджекта", "  Eject size which will be substracted from player cell"),
        "ejectDistance": strData("дальнЕджекта", "Как далеко летит еджект после бросания"),
        "ejectCooldown": strData("откактЕджекта", "Кол-во тиков до того как игрок может опять бросать еджект (1 тик = 40 мс)"),
        "foodMinSize": strData("минРазмЕды", "Минимальный размер еды"),
        "foodMinAmount": strData("минКолЕды", "Минимальное кол-во еды на карте"),
        "virusMinSize": strData("минРазмВируса", "Минимальный размер вируса"),
        "virusMinAmount": strData("минКолВирусов", "Минимальное количество вирусов на карте"),
        "speedBoosterMinAmount": strData("минКолБустовСкор", "Кол-во бустеров(поверапов) скорости"),
        "speedBoosterTime": strData("длитДейстБустовСкор", "Длительность действия бустера скорости"),
        "speedBoosterValue": strData("силаБустаСкорости", "Множитель скорости (1.5 = на 50% быстрее, 0.5 = на 50% медленнее"),
        "speedBoosterSize": strData("размерБустаСкорости", "На сколько большой бустер скорости"),
        "mergeBoosterMinAmount": strData("минКолБустовСлияния", "Кол-во бустеров слияния/соединения"),
        "mergeBoosterTime": strData("длитДейстБустовСлияния", "Длительность действия бустера слияния"),
        "mergeBoosterValue": strData("силаБустаСлияния", "Множитель задержки соединения (1.5 = на 50% быстрее, 0.5 = на 50% медленнее"),
        "mergeBoosterSize": strData("размерБустаСлияния", "На сколько большой бустер слияния"),
        "virusBoosterMinAmount": strData("минКолБустовВируса", "Кол-во бустеров вируса (игрок становится колючкой)"),
        "virusBoosterTime": strData("длитДейстБустовВируса", "Длительность действия бустеров вируса (игрок становится колючкой)"),
        "virusBoosterSize": strData("размерБустаВируса", "На сколько большой бустер вируса"),
        "sizeBoosterMinAmount": strData("минКолБустовРазмера", "Кол-во бустеров размера (игрок растет сам по себе)"),
        "sizeBoosterTime": strData("длитДейстБустовРазмера", "Длительность действия бустера размера (игрок растет сам по себе)"),
    },
    // uk: {},
    // ar: {},
    // es: {},
    // fr: {},
    // tr: {},
    // pt: {},
    // de: {},
}

function strData(name, desc) {
    return {
        n: name,
        d: desc
    }
}

module.exports = CONFIG_NAMES;
