var CONFIG_NAMES = {
    en: {
        "playerStartMass": strData(null, "حجم بداية اللاعب"),
        "playerMaxCells": strData(null, "أكبر عدد من الخلايا المسموح بها لكل لاعب"),
        "playerSpeed": strData(null, "مضاعف سرعة اللاعب،2= سرعة مضاعفة، 1= سرعة عادية"),
        "playerDecayRate": strData(null, "الحجم الذي يتم فقدانه كل ثانية"),
        "playerRecombineTime": strData(null, "الوقت الذي يحتاجه اللاعب قبل أن يتجمع"),
        "ejectSize": strData(null, "حجم الطعام"),
        "ejectSizeLoss": strData(null, "الحجم الذي سيتم فقدانه من اللاعب"),
        "ejectDistance": strData(null, "مسافة التطعيم"),
        "ejectCooldown": strData(null, "المدة بعد كل تطعيم، 1= 40 جمث"),
        "foodMinSize": strData(null, "أصغر حجم للطعام"),
        "foodMinAmount": strData(null, "أقل عدد خلايا الطعام"),
        "virusMinSize": strData(null, "أقل حجم للفيروس"),
        "virusMinAmount": strData(null, "أقل عدد من الفيروسات في الخريطة"),
        "speedBoosterMinAmount": strData(null, "أصغر مدة استعمال لرافع القوة"),
        "speedBoosterTime": strData(null, "مدة اشتغال رافع القوة"),
        "speedBoosterValue": strData(null, "مضاعف السرعة، 1.5= ٪50 أسرع، 0.5= ٪50 أبطأ"),
        "speedBoosterSize": strData(null, "حجم رافع القوة"),
        "mergeBoosterMinAmount": strData(null, "أصغر كمية لقوة التجمع"),
        "mergeBoosterTime": strData(null, "مدة اشتغال قوة التجمع"),
        "mergeBoosterValue": strData(null, "مضاعف وقت قوة التجمع، 0.5= ٪50 أسرع، 1.5= ٪50 أبطأ"),
        "mergeBoosterSize": strData(null, "حجم قوة التجمع"),
        "virusBoosterMinAmount": strData(null, "أصغر كمية لقوة الفيروس"),
        "virusBoosterTime": strData(null, "مدة اشتغال قوة الفيروس", "مدة اشتغال قوة الفيروس"),
        "virusBoosterSize": strData(null, "حجم قوة الفيروس"),
        "sizeBoosterMinAmount": strData(null, "أصغر كمية لقوة زيادة الحجم"),
        "sizeBoosterTime": strData(null, "مدة اشتغال قوة زيادة الحجم"),
    },
    ru: {
        "playerStartMass": strData("حجم بداية اللاعب", "حجم البداية"),
        "playerMaxCells": strData("أكبر عدد من الخلايا المسموح بها لكل لاعب", "أكبر عدد خلايا"),
        "playerSpeed": strData("مضاعف سرعة اللاعب،2= سرعة مضاعفة، 1= سرعة عادية"),
        "playerDecayRate": strData("الحجم الذي يتم فقدانه كل ثانية", "معدل الصغر"),
        "playerRecombineTime": strData("الوقت الذي يحتاجه اللاعب قبل أن يتجمع", "وقت التجمع"),
        "ejectSize": strData("حجم الطعام", "حجم الطعام"),
        "ejectSizeLoss": strData("الحجم الذي سيتم فقدانه من اللاعب", "الحجم المفقود في التطعيم"),
        "ejectDistance": strData("مسافة التطعيم", "مسافة التطعيم"),
        "ejectCooldown": strData("المدة بعد كل تطعيم، 1= 40 جمث", "هدنة ما بعد التطعيم"),
        "foodMinSize": strData("أصغر حجم للطعام", "أصغر حجم للطعام"),
        "foodMinAmount": strData("أقل عدد خلايا الطعام", "أصغر كمية من الطعام"),
        "virusMinSize": strData("أقل حجم للفيروس", "أصغر حجم للفيروس"),
        "virusMinAmount": strData("أقل عدد من الفيروسات في الخريطة", "أصغر كمية فيروسات"),
        "speedBoosterMinAmount": strData("أصغر مدة استعمال لرافع القوة", "أصغر مدة استعمال لرافع القوة"),
        "speedBoosterTime": strData("مدة اشتغال رافع القوة", "مدة رافع القوة"),
        "speedBoosterValue": strData("مضاعف السرعة، 1.5= ٪50 أسرع، 0.5= ٪50 أبطأ"),
        "speedBoosterSize": strData("حجم رافع القوة", "حجم رافع القوة"),
        "mergeBoosterMinAmount": strData("عدد رافع الطاقة للتجمع", "أصغر كمية لقوة التجمع"),
        "mergeBoosterTime": strData("مدة قوة التجمع", "مدة قوة التجمع"),
        "mergeBoosterValue": strData("مضاعف وقت قوة التجمع، 0.5= ٪50 أسرع، 1.5= ٪50 أبطأ", "قيمة قوة التجمع"),
        "mergeBoosterSize": strData("كم حجم رافع الطاقة", "حجم قوة التجمع"),
        "virusBoosterMinAmount": strData("أصغر كمية لقوة الفيروس", "أصغر كمية لقوة الفيروس"),
        "virusBoosterTime": strData("مدة قوة الفيروس", "مدة قوة الفيروس"),
        "virusBoosterSize": strData("حجم قوة الفيروس", "حجم قوة الفيروس"),
        "sizeBoosterMinAmount": strData("أصغر كمية لقوة زيادة الحجم", "أصغر كمية لقوة زيادة الحجم"),
        "sizeBoosterTime": strData("مدة قوة زيادة الحجم", "مدة قوة زيادة الحجم"),
    },
    // uk: {},
    // ar: {},
    // es: {},
    // fr: {},
    // tr: {},
    // pt: {},
    // de: {},
}

function strData(name, desc) {
    return {
        n: name,
        d: desc
    }
}

module.exports = CONFIG_NAMES;
